package GUIController;

public enum Pages {
    MAIN_MENU,
    LOGIN_PAGE,
    COURSES_LIST,
    COURSE_EDIT,
    COURSE_CREATE,
    PROFESSOR_LIST,
    PROFESSOR_EDIT,
    PROFESSOR_CREATE,
    WEEKLY_SCHEDULE,
    REQUESTS,
    EXAMS,
    RECOMMENDATION,
    RECOMMENDATION_SHOW,
    RECOMMENDATION_CREATE,
    CERTIFICATE_STUDENT,
    MINOR,
    MINOR_REQUEST,
    WITHDRAWAL,
    WITHDRAWAL_REQUEST,
    DORM,
    THESIS_DEFENCE,
    REQUEST_BAR,
    TEMPORARY_SCORES_STUDENT_SIDE,
    REVIEW_STUDENT_SIDE,
    TEMPORARY_SCORES_PEOFESSOR_SIDE,
    REVIEW_PROFESSOR_SIDE,
    EDIT_SCORE,
    TEMPORARY_SCORES_EDUCATIONAL_ASISTANT_SIDE,
    TEMPORARY_SCORES_OF_STUDENT,
    REVIEW_OF_STUDENT,
    COURSE_SUMMARY,
    HOME_PAGE


}
